arsnova:
  ##############################################################################
  # System settings
  ##############################################################################
  system:
    # The URL under which the ARSnova server is reachable. Use
    # http://localhost:8080 for development.
    root-url: https://example.com

    # The path where the ARSnova API is accessible by clients. By default,
    # this path is set to the context path of the backend. If you are running
    # the backend behind a proxy server, you might need to set this path
    # manually.
    api:
      proxy-path: ""

    # Database
    couchdb:
      host: localhost
      port: 5984
      db-name: arsnova3
      create-db: false
      username: admin
      password: ""

    # Mail server
    mail:
      host: ""
      sender-name: ARSnova
      sender-address: ""

    # Message broker for internal service communication
    message-broker:
      rabbitmq:
        enabled: true
        host: localhost
        port: 5672
        username: arsnova
        password: arsnova
        virtual-host: /
        manage-declarations: true
        listener:
          max-attempts: 3
      published-events:
        - entity-type: UserProfile
          event-type: AfterCreation
          included-properties:
            - id
        - entity-type: UserProfile
          event-type: AfterDeletion
          included-properties:
            - id
        - entity-type: Room
          event-type: AfterCreation
          included-properties:
            - id
            - shortId
            - ownerId
        - entity-type: Room
          event-type: AfterDeletion
          included-properties:
            - id
            - shortId
            - ownerId
        - entity-type: Comment
          event-type: BeforeCreation
          included-properties:
            - roomId
            - creatorId
            - body
            - timestamp
            - read
        - entity-type: Content
          event-type: AfterDeletion
          included-properties:
            - id
            - roomId

    caching:
      max-entries: 100000
      expiry: 12H

    # Formatting service
    formatting-service:
      enabled: true
      host-url: http://localhost:3020

    # LMS connector service
    lms-connector:
      enabled: false
      host-url: http://localhost:8080/lms-connector-service
      username: test
      password: test

    inactivity-thresholds:
      # Anonymize user content for users with X days of inactivity.
      anonymize-users: 180

      # Delete guest sessions automatically after X days of owner inactivity.
      delete-guest-rooms: 180

  ##############################################################################
  # Authentication
  ##############################################################################
  security:
    # User accounts with administrative privileges (loginId, authProvider)
    admin-accounts: []
    # After the specified number of login tries the client IP will be banned for
    # several minutes.
    login-try-limit: 50
    # After the specified number of resent emails the client IP will be banned
    # for several minutes from resending.
    resend-mail-limit: 5
    # The number of constraints (like "Has to contain a number") which have to
    # be met.
    password-strictness-level: 2

    # JSON Web Tokens
    jwt:
      server-id: arsnova.backend.v3:example.com
      secret: ""
      validity-period: 6H

    # CORS grants full API access to client-side (browser) applications from
    # other domains. Untrusted and vulnerable applications running on these
    # domains pose a security risk to ARSnova users.
    cors-origins: []

    authentication-providers:
      # Guest authentication
      guest:
        enabled: true
        allowed-roles:
          - moderator
          - participant
        order: 0

      # Internal authentication
      #
      # Specific parameters:
      # activation-path: URL of the account activation page
      # allowed-email-domains: Allows you to restrict registration to specific
      #     domains. You can use wildcards (*), e. g. *.*.example.com. Multiple
      #     entries are separated by commas.
      # registration-mail.subject: Subject used for registration e-mail
      # registration-mail.body: Text body used for registration e-mail. {0} will
      #     be replaced by the value of activation-path.
      registered:
        enabled: true
        allowed-roles:
          - moderator
          - participant
        title: ARSnova
        order: 0
        allowed-email-domains:
          - "*"
        registration-mail-subject: "{0} is your ARSnova verification code"
        registration-mail-body: |-
          Welcome to ARSnova!

          Here is the verification code you need for your first login to ARSnova:

              {0}

          {1}
        reset-password-mail-subject: "{0} is your ARSnova verification code"
        reset-password-mail-body: |-
          You requested to reset your password.

          Here is the verification code you need to set a new password:

              {0}

          {1}

      # LDAP authentication
      #
      # Specific parameters:
      # url: LDAP server URL
      # user-dn-pattern: Pattern used to check user credentials against the LDAP
      #     server. {0} will be replaced with the user ID by ARSnova.
      ldap:
        - enabled: false
          allowed-roles:
            - moderator
            - participant
          title: LDAP
          order: 0
          host-url: ldaps://example.com:636/dc=example,dc=com
          user-dn-pattern: uid={0},ou=arsnova
          user-id-attribute: uid
          # Set the following properties if you want to use LDAP search instead
          # of binding with a DN pattern
          user-search-filter: (uid={0})
          user-search-base: ou=people
          # Configure the LDAP manager user if anonymous binding is not allowed
          manager-user-dn: cn=arsnova-manager,dc=example,dc=com
          manager-password: arsnova
          # Timeout for establishing a connection in milliseconds
          connect-timeout: 5000

      # SAML authentication
      saml:
        enabled: false
        allowed-roles:
          - moderator
          - participant
        title: SAML
        order: 0
        idp:
          meta-file: saml-idp.xml
          entity-id: ""
        sp:
          meta-file: ""
          entity-id: ""
        keystore:
          file: arsnova.p12
          store-password: arsnova
          key-alias: saml
          key-password: arsnova
        user-id-attribute: uid
        assertion-consumer-service-index: 0
        max-authentication-lifetime: 3600

      # CAS authentication
      cas:
        enabled: false
        allowed-roles:
          - moderator
          - participant
        title: CAS
        order: 0
        host-url: https://example.com/cas

      # OpenID Connect authentication
      oidc:
        - enabled: false
          allowed-roles:
            - moderator
            - participant
          title: OIDC
          order: 0
          issuer: https://example.com/oidc
          client-id: ""
          secret: ""

      # OAuth authentication with third party services
      # Specific parameters:
      # key: OAuth key/id provided by a third party auth service
      # secret: OAuth secret provided by a third party auth service
      oauth:
        facebook:
          enabled: false
          allowed-roles:
            - moderator
            - participant
          order: 0
          key: ""
          secret: ""
        twitter:
          enabled: false
          allowed-roles:
            - moderator
            - participant
          order: 0
          key: ""
          secret: ""
        google:
          enabled: false
          allowed-roles:
            - moderator
            - participant
          order: 0
          key: ""
          secret: ""

  ##############################################################################
  # Templates
  ##############################################################################
  templates:
    # Placeholders for room invitation:
    # {0}: room short ID, {1}: token, {2}: root URL, {3}: room invitation URL,
    # {4}: room name
    room-invitation-url: "{2}/redeem-token/{0}/token/{1}"
    room-invitation-mail-subject: "Access to room {4} granted"
    room-invitation-mail-body: |-
      Hello!

      You have been invited to the ARSnova room "{4}". Please use the following link so the access permissions can be assigned to your account:

          {3}

      {2}

  ##############################################################################
  # User interface
  ##############################################################################
  ui:
    # Links which are displayed by the client
    links:
      help:
        url: https://particify.de/manual/
      imprint:
        url: ""
      privacy:
        url: ""

    # It is possible to use an external tracking software with ARSnova.
    # Currently Matomo is the only supported tracking provider.
    tracking:
      provider: matomo
      tracker-url: ""
      site-id: ""
