arsnova:
  ################################################################################
  # General server settings
  ################################################################################

  # The URL under which the ARSnova server is reachable. Use
  # http://localhost:8080 for development.
  root-url: https://example.com

  # The path where the ARSnova API is accessible by clients. By default, this path
  # is set to the context path of the backend. If you are running the backend
  # behind a proxy server, you might need to set this path manually.
  api:
    path: /api

  # The context paths where the ARSnova modules have been deployed
  customization:
    path: /customization
  mobile:
    path: /mobile
  presenter:
    path: /presenter

  # WebSocket server
  socketio:
    bind-address: localhost
    port: 8090
    ssl:
      # To enable SSL for Socket.IO you have to import your key and certificate files into a Java Key Store. If you tunnel
      # WebSocket connections through a proxy server, you can skip this configuration.
      # See https://docs.oracle.com/javase/8/docs/technotes/tools/unix/keytool.html
      jks-file: /etc/arsnova/arsnova.jks
      jks-password: arsnova
    proxy-path: /socket.io

  ################################################################################
  # Database
  ################################################################################
  couchdb:
    host: localhost
    port: 5984
    name: arsnova3
    username: admin
    password: ""
    migrate-from: arsnova

  ################################################################################
  # E-Mail
  ################################################################################
  mail:
    sender:
      name: ARSnova
      address: ""
    host: ""

  ################################################################################
  # Authentication
  ################################################################################
  security:
    # Admin accounts
    # Usernames of the accounts which are allowed to manage global messages of the
    # day. Multiple accounts are separated by commas.
    admin-accounts: ""
    authentication:
      # After the specified number of login tries the client IP will be banned for
      # several minutes
      login-try-limit: 50

    # JSON Web Tokens
    jwt:
      serverId: arsnova.backend.v3:com.example
      secret: ""
      validity-period: T6H

    # CORS grants full API access to client-side (browser) applications from other
    # domains. Multiple entries are separated by commas. Untrusted and vulnerable
    # applications running on these domains pose a security risk to ARSnova users.
    cors:
      origins: https://

    # Guest authentication
    guest:
      enabled: true
      allowed-roles: speaker,student
      order: 0

    # Setup combined login if you want to use a single, customized login page
    # which is used for multiple authentication services.
    custom-login:
      enabled: false
      allowed-roles: speaker,student
      title: University
      login-dialog-path: ""
      image: ""
      order: 0

    # Internal authentication
    #
    # Specific parameters:
    # activation-path: URL of the account activation page
    # allowed-email-domains: Allows you to restrict registration to specific
    #     domains. You can use wildcards (*), e. g. *.*.example.com. Multiple
    #     entries are separated by commas.
    # registration-mail.subject: Subject used for registration e-mail
    # registration-mail.body: Text body used for registration e-mail. {0} will be
    #     replaced by the value of activation-path.
    user-db:
      enabled: true
      allowed-roles: speaker,student
      title: ARSnova
      login-dialog-path: account.html
      activation-path: account.html
      reset-password-path: account.html
      image: ""
      order: 0
      allowed-email-domains: '*'
      registration-mail:
        subject: ARSnova Registration
        body: |-
          Welcome to ARSnova!

          Please confirm your registration by visiting the following web address:
          {0}

          Afterwards, you can log into ARSnova with your e-mail address and password.
      reset-password-mail:
        subject: ARSnova Password Reset
        body: |-
          You requested to reset your password.

          Please follow the link below to set a new password:
          {0}

    # LDAP authentication
    #
    # Specific parameters:
    # url: LDAP server URL
    # user-dn-pattern: Pattern used to check user credentials against the LDAP
    #     server. {0} will be replaced with the user ID by ARSnova.
    ldap:
      enabled: false
      allowed-roles: speaker,student
      title: LDAP
      login-dialog-path: login-ldap.html
      image: ""
      order: 0
      url: ldaps://example.com:636/dc=example,dc=com
      user-dn-pattern: uid={0},ou=arsnova
      # Set the following properties if you want to use LDAP search instead of binding
      # with a DN pattern
      user-search-filter: (uid={0})
      user-search-base: '"ou=people"'
      # Configure the LDAP manager user if anonymous binding is not allowed
      manager-user-dn: cn=arsnova-manager,dc=example,dc=com
      manager-password: arsnova

    # CAS authentication
    cas:
      enabled: false
      allowed-roles: speaker,student
      title: CAS
      image: ""
      order: 0
    cas-server-url: https://example.com/cas

    # OpenID Connect authentication
    oidc:
      enabled: false
      allowed-roles: speaker,student
      title: OIDC
      image: ""
      order: 0
      issuer: https://example.com/oidc
      client-id: ""
      secret: ""

    # OAuth authentication with third party services
    # Specific parameters:
    # key: OAuth key/id provided by a third party auth service
    # secret: OAuth secret provided by a third party auth service
    facebook:
      enabled: false
      allowed-roles: speaker,student
      order: 0
      key: ""
      secret: ""
    twitter:
      enabled: false
      allowed-roles: speaker,student
      order: 0
      key: ""
      secret: ""
    google:
      enabled: false
      allowed-roles: speaker,student
      order: 0
      key: ""
      secret: ""

  messaging:
    relay:
      enabled: false
      host: localhost
      port: 61613
      user: arsnova
      password: arsnova

  ################################################################################
  # ARSnova Connector (for LMS)
  ################################################################################
  connector:
    enable: false
    uri: http://localhost:8080/connector-service
    username: test
    password: test

  ################################################################################
  # Features
  ################################################################################
  features:
    mathjax:
      # Enable MathJax to allow the use of Math formulas written in TeX syntax in
      # text fields.
      enabled: true
      src: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js

    # The following features are considered experimental because they have not been
    # tested in a production environment over a longer time frame and/or their
    # behavior will change in future releases.
    freetext-imageanswer:
      enabled: true
    question-format:
      grid-square:
        enabled: true

    # Without enabled session-import-export feature no sessions can be added to the
    # public pool
    session-import-export:
      enabled: true
    public-pool:
      enabled: true
    export-to-click:
      enabled: true

  ################################################################################
  # Customization
  ################################################################################
  feedback:
    # Minutes, after which the feedback is deleted
    cleanup: 10
    # Number of "you've lost me"/"abgehängt" votes, starting to show warning sign
    warning: 15
  upload:
    # Maximal filesize in bytes
    filesize_b: 4194304
  imageupload:
    thumbnail:
      # Maximal thumbnail size in pixels
      width: 400
      height: 400
  question:
    # Maximal number of answer options allowed for a skill question
    answer-option-limit: 8
    # Enable Markdown and MathJax parsing in answer options. Formatting in answer
    # options should be used cautiously since it could lead to display errors.
    # Answer options will still not be parsed in diagrams. This setting has no
    # effect if neither MathJax nor Markdown are enabled.
    parse-answer-option-formatting: false
  session:
    # Demo session id to show above session login button
    # You can freely use the demo session of https://arsnova.eu/mobile which can be
    # imported from the repro:
    # https://github.com/thm-projects/arsnova-mobile/tree/master/demo-sessions
    demo-id: ""
    guest-session:
      # Delete guest sessions automatically after X days of owner inactivity.
      cleanup-days: 180
  user:
    # Anonymize user content for users with X days of inactivity
    cleanup-days: 180
  ui:
    # Label underneath ARSnova logo
    slogan: Audience Response System

    # Splashscreen configuration
    # Best results are achieved with logos that have the same width and height.
    splashscreen:
      logo-path: resources/images/arsnova-logo.png
      slogan: Audience Response System
      min-delay: 3000

      # Splash screen colors
      # These settings override the default colors of the frontend theme.
      slogan-color: ""
      background-color: ""
      loading-ind-color: ""

  # Links which are displayed in the frontend applications
  links:
    blog:
      url: https://arsnova.eu/blog/
    documentation:
      url: https://arsnova.eu/manual/
    presenter-documentation:
      url: ""
    overlay:
      url: https://arsnova.eu/overlay/
    organization:
      url: ""
    imprint:
      url: ""
    privacy-policy:
      url: ""

  # Configuration for the public pool
  pp:
    subjects: Allgemeines,Anglistik,Architektur,Bauingenieurwesen,Betriebswirtschaftslehre,Biologie,Chemie,Elektrotechnik,Geographie,Geowissenschaften,Germanistik,Geschichtswissenschaft,Informatik,Kunst,Kunstpädagogik,Maschinenbau,Mathematik,Medienwissenschaften,Medizin,Musik,Pharmazie,Physik,Psychologie,Rechtswissenschaften,Stadtplanung,Theaterwissenschaften,Theologie,Vermessungswesen,Volkswirtschaftslehre
    licenses: CC by - Attribution,CC nc - Non-Commercial,CC nd - No Derivatives,CC sa - Share Alike,CCO - Public Domain,CC by-nd -  Attribution-No Derivatives,CC by-c - Attribution-Non-Commercial,CC by-nc-sa - Attribution-Non-Derivatives-Share Alike,CC by-nc-nd Attribution-Non-Commercial- No Derivatives,GNU GPL - GNU General Public License
    logofilesize_b: 102400
    # Do not reorder levels. Append new levels to the end of the list. Otherwise,
    # references in existing public sessions could be mixed up.
    session-levels:
      de: Allgemeinbildung,Abitur,Bachelor,Master,Wer wird Millionär,Sonstiges
      en: General Education,Highschool,Bachelor,Master,Who Wants to Be a Millionaire,Miscellaneous

  ################################################################################
  # Tracking
  ################################################################################
  # It is possible to use an external tracking software with ARSnova. Currently
  # Matomo is the only supported tracking provider.
  tracking:
    provider: matomo
    tracker-url: ""
    site-id: ""
