[versions]
aspectj-plugin = "8.6"
aspectj-rt = "1.9.22"
bucket4j = "8.10.1"
checkstyle = "10.12.4"
ektorp = "1.5.0"
guava = "33.1.0-jre"
java-jwt = "4.4.0"
jib-plugin = "3.4.2"
kotlin = "1.9.23"
ktlint-plugin = "12.1.0"
lms-connector = "1.0.2"
pac4j = "5.7.3"
spotbugs-annotations = "4.8.4"
spotbugs-plugin = "6.0.12"
spring-boot-plugin = "3.2.5"
spring-cloud = "2023.0.1"
springmockk = "4.0.2"

[libraries]
aspectj-rt = { module = "org.aspectj:aspectjrt", version.ref = "aspectj-rt" }
bucket4j = { module = "com.bucket4j:bucket4j-core", version.ref = "bucket4j" }
ektorp = { module = "org.ektorp:org.ektorp", version.ref = "ektorp" }
ektorp-spring = { module = "org.ektorp:org.ektorp.spring", version.ref = "ektorp" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
java-jwt = { module = "com.auth0:java-jwt", version.ref = "java-jwt" }
lms-connector = { module = "net.particify.arsnova.integrations:connector-client", version.ref = "lms-connector" }
pac4j-jakartaee = { module = "org.pac4j:pac4j-jakartaee", version.ref = "pac4j" }
pac4j-oauth = { module = "org.pac4j:pac4j-oauth", version.ref = "pac4j" }
pac4j-oidc = { module = "org.pac4j:pac4j-oidc", version.ref = "pac4j" }
pac4j-saml = { module = "org.pac4j:pac4j-saml", version.ref = "pac4j" }
spotbugs-annotations = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "spotbugs-annotations" }
spring-cloud = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "spring-cloud" }
springmockk = { module = "com.ninja-squad:springmockk", version.ref = "springmockk" }

[plugins]
aspectj = { id = "io.freefair.aspectj.post-compile-weaving", version.ref = "aspectj-plugin" }
jib = { id = "com.google.cloud.tools.jib", version.ref = "jib-plugin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs-plugin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot-plugin" }
