logging:
  exception-depth: full

spring:
  liquibase:
    contexts: dev

security:
  jwt:
    issuer: arsnova.backend.v3:example.com
    secret: weaksecret1234567890123456789012
  challenge:
    secret: weaksecret1234567890123456789012
  saml2:
    # credentials-path is only used in dev environment to simplify overriding with environment variables.
    credentials-path: file:credentials
    relyingparty:
      registration:
        fc62cd95-bea9-4aa3-987d-fa976ef300f3:
          entity-id: http://arsnova-server-core4:8080/api/saml2/service-provider-metadata/{registrationId}
          attribute-mapping:
            mail-address: urn:oid:1.2.840.113549.1.9.1
          signing:
            credentials:
              - private-key-location: ${security.saml2.credentials-path}/rp.key
                certificate-location: ${security.saml2.credentials-path}/rp.crt
          assertingparty:
            metadata-uri: http://keycloak:8080/realms/dev/protocol/saml/descriptor

persistence:
  v3-migration:
    authentication-provider-mapping:
      SAML: fc62cd95-bea9-4aa3-987d-fa976ef300f3

mail:
  sender-address: arsnova@localhost
  sender-name: arsnova
  host: mailpit
  port: 1025

service:
  root-url: http://localhost:4200
